<?php
/**
 * @file
 * Pinterest Widget for Easy Social module.
 * Developed by Timothy E.
 */

/*
 * Implements hook_easy_social_widget().
 */
function es_pinterest_easy_social_widget() {
  return array(
    'pinterest' => array(
      'name' => 'Pinterest',
      'markup' => '_es_pinterest_widget_pinterest_markup',
      'scripts' => array(
        array(
          'path' => 'http://assets.pinterest.com/js/pinit.js',
          'type' => 'external',
        ),
      ),
      'styles' => array(
        array(
          'path' => drupal_get_path('module', 'es_pinterest') . '/es_pinterest.css', 
          'type' => 'module',
        ),
      ),
    ),
  );
}


/*
 * Implements _mymodule_widget_widgetname_markup().
 */
function _es_pinterest_widget_pinterest_markup($url, $type, $title = NULL, $lang = 'en') {
  return <<<HTML
<div class="es_pinterest_wrapper">
<a href="//www.pinterest.com/pin/create/button/?url={$url}&media=http%3A%2F%2Ffarm8.staticflickr.com%2F7027%2F6851755809_df5b2051c9_z.jpg&description=Pin%20it." data-pin-do="buttonPin" data-pin-config="above" data-pin-color="red" data-pin-height="28"><img src="//assets.pinterest.com/images/pidgets/pinit_fg_en_rect_red_28.png" /></a>
</div>
HTML;
}
